CREATE TABLE SHIPPERS(
    SHIPPER_ID INT NOT NULL,
    COMPANY_NAME VARCHAR(20) NOT NULL,
    PHONE VARCHAR(20) DEFAULT NULL
); 
ALTER TABLE SHIPPERS ADD CONSTRAINT CONSTRAINT_F PRIMARY KEY(SHIPPER_ID);        
-- 3 +/- SELECT COUNT(*) FROM SHIPPERS; 
INSERT INTO SHIPPERS(SHIPPER_ID, COMPANY_NAME, PHONE) VALUES
(1, 'Speedy Express', '(503) 555-9831'),
(2, 'United Package', '(503) 555-3199'),
(3, 'Federal Shipping', '(503) 555-9931');               
