http://localhost:3000/api/categories
###
http://localhost:3200/api/suppliers
###
http://localhost:3300/api/shippers
###

http://localhost:8080/api/categories
###
http://localhost:8080/api/suppliers
###
http://localhost:8080/api/shippers
###
http://localhost:8080/api/categories/2
###
http://localhost:8080/api/suppliers/2
###
http://localhost:8080/api/shippers/2
###

http://localhost:3000/actuator

###
http://localhost:3000/actuator/health
###
http://localhost:3000/actuator/info
###
http://localhost:3000/actuator/metrics
###
http://localhost:3000/actuator/beans
###